---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ansible
      location: westus2
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansible
      name: ansible.vnet
      address_prefixes: "10.100.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansible
      name: vm.sn
      address_prefix: "10.100.1.0/24"
      virtual_network: ansible.vnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ansible
      allocation_method: Static
      name: ansiblepip
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: ansible
      name: ansiblensg
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: ansible
      name: ansiblevnic
      virtual_network: ansible.vnet
      subnet: vm.sn
      public_ip_name: ansiblepip
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ansible
      name: kafkan1
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_passwrod: Netapp123!
      network_interfaces: ansiblevnic
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
...
